language: node_js
branches:
  only:
  - master
node_js:
  - 8
cache:
  directories:
    - node_modules
matrix:
  fast_finish: true
before_script:
  - npm install -g serverless
script: 
  - npm install
  - sls deploy --stage dev
  - npm test